logging:
  file: logs/mod-workflow.log
  level:
    org:
      folio: INFO
      hibernate: INFO
      springframework: INFO
  path:

server:
  port: 9000

spring:
  activemq.broker-url: tcp://localhost:61616
  application.name: mod-workflow
  data.rest:
    returnBodyOnCreate: true
    returnBodyOnUpdate: true
  datasource:
    platform: h2
    url: jdbc:h2:./target/mod-workflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    # platform: postgres
    # driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/mod-workflow

    username: folio
    password: folio
  h2:
    console:
      enabled: true
      path: /h2console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # database-platform: org.hibernate.dialect.PostgreSQLDialect

    properties.hibernate.jdbc.lob.non_contextual_creation: true
    generate-ddl: false
    hibernate.ddl-auto: none
    open-in-view: true
    show-sql: false
  profiles:
    active: default
  thymeleaf:
    mode: TEXT
    suffix: .sql

event.queue.name: event.queue

tenant:
  header-name: X-Okapi-Tenant
  force-tenant: false
  default-tenant: diku
  initialize-default-tenant: true
  domain-packages:
  schema-scripts:

okapi.location: http://localhost:9130
